version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./www:/app/public
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web

  php:
    image: php:8.4-fpm
    container_name: php
    volumes:
      - ./www:/app/public
    networks:
      - web

networks:
  web:
    driver: bridge
